title: Weinan Gong
logo: /portfolio images/rounded_self_image.jpg
description:  Data Scientist | Ph.D. Candidate in Economics | Experimental & Behavioral Economist
# show_downloads: true
theme: jekyll-theme-minimal
